# Sorting, searching, and counting

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

In [5]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [7]:
x = np.array([[1,4],[3,1]])
np.sort(x,axis=1) # сортировка массива по указанной оси

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [33]:
surnames =    ('Hertz',    'Aalilei', 'Hertz')
first_names = ('Heinrich', 'Zalileo', 'Gustav')
np.lexsort([first_names,surnames]) # выводит связанные индексы обратноотсортированных по x ключей массивов

array([1, 2, 0], dtype=int64)

In [34]:
x = ['A','B','C']
y = ['F','E','D']
np.lexsort([y,x]) # выводит связанные индексы обратноотсортированных по x ключей массивов

array([0, 1, 2], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [42]:
x = np.array([[1,4],[3,1]])
np.argsort(x,axis=1) # возвращает индексы, сортирующие элементы исходного массива

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its `fifth` element would be the same as the element of sorted x, and it divide other elements by their value.

In [71]:
x = np.random.permutation(10) # массив случайной сортировки значений до 10
y = np.partition(x,5)
'''
numpy.partition(a, kth, axis=-1, kind='introselect', order=None)
Функция partition() возвращает копию исходного массива элементы которого разделены по указанному значению.

Параметр kth=4 указывает на индекс элемента в отсортированной копии исходного массива,
но в возвращаемом массиве только этот элемент и сохраняет свое положение,
все элементы с меньшим значением переносятся влево, а с большим или равным значением переносятся вправо,
причем порядок элементов слева и справа никак не определен.
'''
print(x,'\t',x[5])
print(y)

[3 8 7 4 5 1 9 0 6 2] 	 1
[1 2 0 3 4 5 6 7 8 9]


Q5. Create the indices of an array such that its `third` element would be the same as the element of sorted x, and it divide other elements by their value.

In [85]:
x = np.random.permutation(10) # массив случайной сортировки значений до 10
partitioned = np.partition(x,3) # возвращает копию исходного массива элементы которого разделены по указанному значению.
index = np.argpartition(x,3) # возвращает массив индексов элементов исходного массива в их разбиении по указанному значению
'''
numpy.argpartition(a, kth, axis=-1, kind='introselect', order=None)
Работа данной функции абсолютно аналогична numpy.partition(),
но вместо копии разделенного исходного массива она возвращает массив индексов его элементов в этом разбиении.
'''
print(x,'\t', x[3])
print(partitioned)
print(index)

[2 7 4 0 6 9 5 3 8 1] 	 0
[0 1 2 3 4 5 7 9 8 6]
[3 9 0 7 2 6 1 5 8 4]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the `second` axis.

In [109]:
x = np.random.permutation(10).reshape(2,5) # массив случайной сортировки значений до 10 заданной формы
print(x)
print('ЗНАЧЕНИЯ элементов:')
print(np.min(x,axis=1)) # выводит ЗНАЧЕНИЯ наименьших элементов каждой строки (если axis=1) в одном массиве
print(np.max(x,axis=1)) # выводит ЗНАЧЕНИЯ наибольших каждой строки (если axis=1) в одном массиве
print('ИНДЕКСЫ элементов:')
print(np.argmin(x,axis=1)) # выводит ИНДЕКСЫ наименьших элементов каждой строки (если axis=1) в одном массиве
print(np.argmax(x,axis=1)) # выводит ИНДЕКСЫ наибольших каждой строки (если axis=1) в одном массиве

[[6 2 9 3 1]
 [8 0 4 5 7]]
ЗНАЧЕНИЯ элементов:
[1 0]
[9 8]
ИНДЕКСЫ элементов:
[4 1]
[2 0]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [115]:
x = np.array([[np.nan, 4, 3], [3, -2, np.nan]])
print(x)
'''
ниже ИГНОРИРУЮТСЯ nan-значения массива x
'''
print('ЗНАЧЕНИЯ элементов:')
print(np.nanmin(x,axis=1)) # выводит ЗНАЧЕНИЯ наименьших элементов каждой строки (если axis=1) в одном массиве, игнорируя nan-значения
print(np.nanmax(x,axis=1)) # выводит ЗНАЧЕНИЯ наибольших каждой строки (если axis=1) в одном массиве, игнорируя nan-значения
print('ИНДЕКСЫ элементов:')
print(np.nanargmin(x,axis=1)) # выводит ИНДЕКСЫ наименьших элементов каждой строки (если axis=1) в одном массиве, игнорируя nan-значения
print(np.nanargmax(x,axis=1)) # выводит ИНДЕКСЫ наибольших каждой строки (если axis=1) в одном массиве, игнорируя nan-значения

[[nan  4.  3.]
 [ 3. -2. nan]]
ЗНАЧЕНИЯ элементов:
[ 3. -2.]
[4. 3.]
ИНДЕКСЫ элементов:
[2 1]
[1 0]


Q8. Get the `values` and `indices` of the elements that are `bigger` than `2` in x.


In [134]:
x = np.array([[1, 2, 3], [1, 3, 5]])
'''
numpy.nonzero(a)
грубо говоря выводит кортеж разнесенных координат найденых чисел: так например,
у первой тройки координаты (0,2) (т.е. располож в 1-ой строке и 3-ем столбце),
у второй тройки координаты (1,1) (т.е. располож во 2-ой строке и 2-ом столбце),
у пятерки координаты (1,2) (т.е. располож во 2-ой строке и 3-ем столбце).
Эти значения координат разнесены по разным массивам (разделение по осям)
'''
print(x)
print('Значения, которые больше 2-х: {}'.format(x[x>2]))
print( 'Их индексы: {}'.format(np.nonzero(x>2)) )

[[1 2 3]
 [1 3 5]]
Значения, которые больше 2-х: [3 3 5]
Их индексы: (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the `indices` of the elements that are `bigger` than `2` in the `flattend x`.

In [136]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x>2) # возвращает индексы ненулевых элементов в сжатом до одной оси представлении указанного массива

array([2, 4, 5], dtype=int64)

Q10. Check the `elements` of x and return `0` if it is `less than 0`, otherwise `the element itself`.

In [142]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x<0, 0, x) # сравнивает эл-ты с 0 и выдает 0 если True, иначе само число

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the `indices` where elements of `y` should `be inserted` to x to `maintain order`.

In [146]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y) # возвращает индексы в которые должны быть вставлены элементы y, что бы порядок сортировки был сохранен

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [148]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x) # возвращает количество ненулевых элементов массива вдоль указанной оси (если ось не указана, идет расчет по сжатому до 1 оси массиву)

5