# Input and Output

In [1]:
from __future__ import print_function
import numpy as np

In [2]:
author = "kyubyong. https://github.com/Kyubyong/numpy_exercises"

In [3]:
np.__version__

'1.18.1'

In [4]:
from datetime import date
print(date.today())

2020-03-31


## NumPy binary files (NPY, NPZ)

Q1. Save x into `temp.npy` and load it.

In [7]:
x = np.arange(10)

file_name = 'temp.npy' # задаем название файла, 
np.save(file_name, x) # сохраняет массив в двоичном файле формата npy.
y = np.load(file_name) # загружает массивы из файлов формата .npy или .npz, а также pickle объектов и pickle файлов.

np.array_equal(x,y) # вывод результата сравнения массивов

True

Q2. Save x and y into a single file 'temp.npz' and load it.

In [44]:
x = np.arange(10)
y = np.arange(11, 20)
np.savez('temp.npz', x=x,y=y) # cохраняет нескольких массивов в несжатом .npz файле (в формате, похожем на словарь)

z = np.load('temp.npz')
for key in z:
    print ('{}:{}'.format(key, z[key]))

print(np.array_equal(x, z['x'])) # вывод результата сравнения массивов по форме и элементам
print(np.array_equal(y, z['y'])) # вывод результата сравнения массивов по форме и элементам

x:[0 1 2 3 4 5 6 7 8 9]
y:[11 12 13 14 15 16 17 18 19]
True
True


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [57]:
x = np.arange(10).reshape(2, 5)
header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt',x) # сохраняет массив в текстовый файл (1 или 2-х мерный массив NumPy или подобный массиву объект)
np.loadtxt('temp.txt') # выводит массив из текстового файла

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [72]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)
np.savetxt('temp.txt',(x,y,z)) # сохраняет массивы в текстовый файл, каждый с новой строки
file = np.loadtxt('temp.txt') # выводит массив из текстового файла
file, file[0] # можно обращаться к опред. элементу массива через индекс

(array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
        [22., 23., 24., 25., 26., 27., 28., 29., 30., 31.]]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

Q5. Convert `x` into bytes, and load it as array.

In [97]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tostring() # конвертация массива в побайтовую строку
print(x_bytes)
x2 = np.frombuffer(x_bytes, dtype=x.dtype) # интерпретирует буфер как одномерный массив (dtype=int)
print(np.array_equal(x,x2))

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00'
True


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [134]:
a = [[1, 2], [3, 4]]
x = np.array(a) # создание ndarray из данного списка
a2 = x.tolist() # преобразует массив NumPy в список Python
print(a==a2)

True


## String formatting

Q7. Convert `x` to a string, and revert it.

In [154]:
x = np.arange(10).reshape(2,5)
x_str = str(x) # преобразуем массив в строку
# print(x_str, "\n", type(x_str))

x_str = x_str.replace('[','').replace(']','') # [] убираем из строки
x2 = np.fromstring(x_str, dtype=x.dtype, sep=" ") # создает новый одномерный массив, который заполнен данными из указанной строки
x2.reshape(x.shape) # предаём форму исходного массива

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Text formatting options

Q8. Print `x` such that all elements are displayed with precision=1, no suppress.

In [182]:
x = np.random.uniform(size=[10,100]) # создание массива указанной размерности с выборкой из равномерного распределения
np.set_printoptions(precision=1, suppress=True) # позволяет настроить параметры вывода массивов на экран ("precision"-кол-во знаков после запятой; "suppress"-показывать полотно целиком или скрывать)
print('размерность :{} \nмассив{}'.format(x.shape,x))

размерность :(10, 100) 
массив[[0.8 0.7 0.8 0.4 0.8 0.6 0.5 0.1 0.7 0.4 0.8 0.1 0.4 0.5 0.4 0.4 0.6 0.6
  0.2 0.9 0.8 0.5 0.6 0.5 0.1 0.7 0.9 0.8 0.2 0.8 0.6 0.4 0.7 0.8 0.8 0.7
  0.7 0.9 0.9 0.9 0.  0.3 0.1 0.6 0.6 0.2 0.8 0.6 0.2 0.3 0.4 0.2 0.  0.3
  0.2 0.4 0.4 0.8 0.4 0.1 0.7 0.4 0.6 0.2 0.  0.4 0.6 0.1 0.2 0.2 0.6 0.8
  0.  0.2 0.9 0.2 0.8 0.2 0.  0.9 0.5 0.6 0.  0.5 0.8 0.4 0.5 0.4 0.5 0.8
  0.1 0.8 0.8 0.7 0.1 0.4 0.6 0.7 0.4 0.3]
 [0.  1.  0.2 0.9 0.3 0.9 0.6 0.7 0.5 0.4 0.1 0.3 0.3 0.6 0.1 0.5 0.2 0.7
  0.6 0.6 0.3 0.4 0.6 0.2 0.5 0.4 0.4 0.7 0.4 0.7 0.9 0.6 0.6 0.3 0.4 0.7
  0.3 0.4 0.9 1.  0.7 0.3 0.1 0.8 1.  0.9 0.2 0.8 0.4 0.9 0.7 0.4 0.5 0.2
  0.3 0.1 0.1 0.9 0.7 0.3 0.9 0.4 0.9 0.1 0.6 0.9 0.8 0.4 0.4 0.7 0.4 0.3
  1.  0.6 0.9 0.6 0.5 0.5 0.2 0.5 0.4 0.5 0.4 0.7 0.9 0.9 0.1 0.9 0.1 0.2
  0.1 0.9 0.6 0.6 0.7 0.5 0.9 0.1 0.2 0.3]
 [0.5 0.2 0.5 0.8 0.7 0.9 1.  0.2 0.1 0.6 0.5 0.8 0.6 0.1 0.8 0.5 0.6 0.1
  0.5 0.3 0.1 1.  1.  1.  0.2 0.2 0.2 0.7 0.8 1.  0.6 0.5 0.2 0.2 0.8 

## Base-n representations

Q9. Convert 12 into a binary number in string format.

In [210]:
bin(12)[2:] # вывод 10-чного числа в бинарном формате

'1100'

Q10. Convert 12 into a hexadecimal number in string format.

In [211]:
hex(12)[2:] # вывод 10-ичного числа в 16-ричном формате

'c'