# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Matrix and vector products

Q1. Predict the results of the following code.

In [14]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(x,'|',y)
print('{} - "np.dot": вычисляет скалярное произведение двух массивов'.format(np.dot(x, y))) # вычисляет скалярное произведение двух массивов
print('{} - "np.dot": вычисляет скалярное произведение двух массивов (строку х с каждым столбцом у)'.format(np.dot(y, x))) # вычисляет скалярное произведение двух массивов (строку х с каждым столбцом у)
print('{} - "np.matmul": вычисляет матричное произведение двух массивов'.format(np.matmul(x, y))) # вычисляет матричное произведение двух массивов
print('{} - "np.matmul": вычисляет матричное произведение двух массивов (строку х с каждым столбцом у)'.format(np.matmul(y,x))) # вычисляет матричное произведение двух массивов (строку х с каждым столбцом у)
print('{} - "np.inner": сумма произведений по последним осям'.format(np.inner(x, y))) # сумма произведений по последним осям
print('{} - "np.inner": сумма произведений по последним осям'.format(np.inner(y, x))) # сумма произведений по последним осям

[1, 2] | [[4, 1], [2, 2]]
[8 5] - "np.dot": вычисляет скалярное произведение двух массивов
[6 6] - "np.dot": вычисляет скалярное произведение двух массивов (строку х с каждым столбцом у)
[8 5] - "np.matmul": вычисляет матричное произведение двух массивов
[6 6] - "np.matmul": вычисляет матричное произведение двух массивов (строку х с каждым столбцом у)
[6 6] - "np.inner": сумма произведений по последним осям
[6 6] - "np.inner": сумма произведений по последним осям


Q2. Predict the results of the following code.

In [22]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [41]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y)) # вычисляет cкалярное произведение двух векторов в том числе и комплексных(a1*b1+a2*b2+...+an*bn)
print(np.vdot(y, x)) # вычисляет cкалярное произведение двух векторов в том числе и комплексных(a1*b1+a2*b2+...+an*bn)
print(np.dot(x.flatten(), y.flatten())) # вычисляет cкалярное произведение двух векторов, получившихся из матриц
print(np.inner(x.flatten(), y.flatten())) # сумма произведений по осям векторов
print()
print((x*y),'\n',(x*y).sum())

30
30
30
30

[[ 4  4]
 [10 12]] 
 30


Q4. Predict the results of the following code.

In [43]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y)) # сумма произведений по последним осям векторов
print(np.inner(y, x)) # сумма произведений по последним осям векторов
print(np.outer(x, y)) # вычисляет внешнее произведение двух векторов (здесь х-столбцы)
print(np.outer(y, x)) # # вычисляет внешнее произведение двух векторов (здесь х-строки)

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [49]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x) # выполняет разложение Холецкого
L

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [198]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q,r = np.linalg.qr(x) # выполняет QR-разложение матрицы

'''
Данное разложение позволяет представить матрицу x в виде произведения qr,
где q - это ортогональная (унитарная) матрица, а r - это верхнетреугольная матрица
'''

print('q={}\n\nr={}'.format(q,r))
assert np.allclose(np.dot(q, r), x) # проверка выполнения условия путем перемножения q на r и сравнения с х ПОЭЛЕМЕНТНО!

q=[[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]

r=[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [90]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U,s,V = np.linalg.svd(x, full_matrices=False ) # выполняет сингулярное (SVD) разложение ('full_matrices'-определяет форму выходных массивов

'''
x - матрица, размерностью (m,n)
U - ортогональная(унитарные для комплексных х) матрица, которая состоит из левых сингулярных векторов (один из размеров будет равен m)
s - диагональная матрица размером (m, n), которая содержит сингулярные числа исходной матрицы х.
V - ортогональная(унитарные для комплексных х) транспонированная матрица, которая состоит из правых сингулярных векторов (один из размеров будет равен n)

Для проверки условия:
1) s_d = np.diag(s) - превращает s из вектора в диагональную матрицу
2) перемножаем матрицы step_2 = s_d и V
3) перемножаем матрицы step_3 = U и step_2
'''

print('U=\n{}\n\ns=\n{}\n\nV=\n{}'.format(U,s,V))
assert np.allclose(np.dot(U, np.dot(np.diag(s), V)), x) # проверка выполнения условия

U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]

s=
[3.       2.236068 2.       0.      ]

V=
[[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [114]:
x = np.diag((1, 2, 3)) # форматирование вектора в диагональную матрицу
eigenvals, eigenvecs = np.linalg.eig(x) # вычисляет собственные числа (значения) и собственные векторы квадратной матрицы
print('диагональная матрица х:\n{}\n\nсобственные числа массива х:\neigenvals=\n{}\n\nсобственный вектор массива х:\neigenvecs=\n{}'.format(x,eigenvals, eigenvecs))

диагональная матрица х:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

собственные числа массива х:
eigenvals=
[1. 2. 3.]

собственный вектор массива х:
eigenvecs=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [107]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals*eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [125]:
x = np.arange(1, 10).reshape((3, 3))
norm_fro = np.linalg.norm(x, ord='fro') # для матриц возвращается норма Фробениуса, для векторов норма не определена;
condition_fro = np.linalg.cond(x, p='fro') # вычисляет число обусловленности матрицы (Данное число позволяет оценить насколько матрица далека от матрицы полного ранга или от невырожденности для квадратной матрицы) ("p"- позволяет указать необходимую при вычислении норму матрицы)
print(norm_fro,condition_fro)

16.881943016134134 4.561770736605098e+17


Q11. Calculate the determinant of x.

In [162]:
x = np.arange(1, 5).reshape((2, 2))
out1 = np.linalg.det(x) # вычисляет детерминант (определитель) матрицы
out2 = x[0,0]*x[1,1]-x[0,1]*x[1,0] # вычисляем определитель вручную

provision = np.allclose(out1,out2) # условие равенства 2х разных вычислений детерминанта
assert (provision)

print(out1)

-2.0000000000000004


Q12. Calculate the rank of x.

In [146]:
x = np.eye(4) # возвращает массив указанной размерности, у которого все элементы по диагонали равны 1, а все остальные равны 0
rank = np.linalg.matrix_rank(x) # вычисляет ранг матрицы с помощью ее SVD разложения
print(rank)

4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [1]:
x = np.arange(1, 5).reshape((2, 2))
sign, lndet= np.linalg.slogdet(x) # вычисляет знак и натуральный логарифм определителя (детерминанта) матрицы.
det = np.linalg.det(x) # вычисляет определитель (детерминант) матрицы

assert ( sign==np.sign(det)) & (lndet==np.log(np.abs(det)) )

print('знак определителя матрицы х: {}\nнатуральный логарифм определителя матрицы х: {}'.format(sign, det))

NameError: name 'np' is not defined

Q14. Return the sum along the diagonal of x.

In [193]:
x = np.eye(4)
sumdiag = np.trace(x) # вычисляет cумму диагональных элементов (след) матрицы
assert x.diagonal().sum()==sumdiag
print(sumdiag)

4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [202]:
x = np.array([[1., 2.], [3., 4.]])
inverse = np.linalg.inv(x) # вычисляет обратную матрицу
assert np.allclose(np.dot(x, inverse), np.eye(2))
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]
